Working conversion without negative prompts
argmaxinc/DiffusionKit pull request #28
Opened 2024-09-01 08:14 UTC by raoulritter

2024-09-02 11:31 UTC, atiorh reviewed
Thanks @raoulritter! Did you test `FLUX.1-schnell` after your changes?

2024-09-02 11:31 UTC, atiorh commented on python/src/diffusionkit/mlx/model_io.py
> +    elif model_key == "FLUX.1-dev":
Shall we consolidate this under `if model_key in ["FLUX.1-schnell", "FLUX.1-dev"]` and dedupe code?

2024-09-02 11:31 UTC, atiorh commented on python/src/diffusionkit/mlx/__init__.py
> +    "FLUX.1-dev": 256,
I believe this should be 512?

2024-09-02 11:31 UTC, atiorh commented on python/test-gen.py
> +import os
Let's remove this file  🙏

2024-09-02 11:31 UTC, atiorh commented on python/src/diffusionkit/mlx/test-conversion-mlx.py
> +import mlx.core as mx
Could you please follow the `UnitTest.TestCase` usage and make this a simple unit test like [this](https://github.com/argmaxinc/DiffusionKit/blob/main/python/src/diffusionkit/tests/mlx/test_diffusion_pipeline.py#L33)? Also, no need to upload to hub from within the test 👍

2024-09-03 14:16 UTC, raoulritter commented
Hey @atiorh, I've made the changes as requested. Just unsure in regards to what you exactly expect from the test-conversion-mlx? Should it be moved to the tests or should it maybe even be deleted as it's not really needed.

2024-09-03 14:45 UTC, atiorh commented
@raoulritter Thanks for the quick iteration! We will revise the testing files, download the ckpt and host it alongside schnell. cc: @arda-argmax

2024-09-04 18:43 UTC, arda-argmax commented
Hey @raoulritter, I have problems running your code. I think you need to make your huggingface checkpoint repo public because I cannot access it. Also, it seems that your branch diverged from our main branch. Can you also rebase it?

2024-09-04 19:13 UTC, raoulritter commented
Hey @arda-argmax,

I think it would perhaps be better based on the conflicts if you guys fixed them according to how you want them instead of me rebasing.  


>I have encountered with problems while trying to run your code. I think you need to make your huggingface checkpoint repo public because I cannot access it`


I previously wrote the following

> Also checking the merge conflicts it appears these are related to the hosting of the checkpoint. Assuming your team will host these checkpoints yourself so won't resolve these for you. 


Let me know if you still want me to take a look but perhaps would make more sense from your side.

2024-09-04 23:04 UTC, arda-argmax commented
I see, sorry I missed it. Can you also share how you run the dev model?

2024-09-06 20:54 UTC, ZachNagengast requested changes
Thanks for contributing, this will be really cool! Tests still need some work to conform to the rest of the repo's style, but added some suggestions to use the argmax HF repo. If we want to follow up with tests in another PR, you may want to just confirm the pipeline is working with the new repo, and take out the current tests for later.

2024-09-06 20:54 UTC, ZachNagengast commented on python/src/diffusionkit/mlx/config.py
> +    guidance_embed=True,  # Add this line
This seems to be an unintentional comment?
```suggestion
    guidance_embed=True,
```

2024-09-06 20:54 UTC, ZachNagengast commented on python/src/diffusionkit/mlx/__init__.py
> +    "FLUX.1-dev": "raoulritter/flux-dev-mlx",
Using argmax repo
```suggestion
    "FLUX.1-dev": "argmaxinc/mlx-FLUX.1-dev",
```

2024-09-06 20:54 UTC, ZachNagengast commented on python/src/diffusionkit/mlx/mmdit.py
> +        timestep_embedding = self.guidance_in(self.t_embedder(timestep))
Override original timestep only for dev model
```suggestion
	if config.guidance_embed:
            timestep = self.guidance_in(self.t_embedder(timestep))
```

2024-09-06 20:54 UTC, ZachNagengast commented on python/src/diffusionkit/mlx/mmdit.py
> +                    timestep_embedding,
Override original timestep only for dev model

```suggestion
                    timestep,
```

2024-09-06 20:54 UTC, ZachNagengast commented on python/src/diffusionkit/mlx/mmdit.py
> +            timestep_embedding
Override original timestep only for dev model

```suggestion
            timestep,
```

2024-09-06 20:54 UTC, ZachNagengast commented on python/src/diffusionkit/mlx/model_io.py
> +    },
Use argmax repo
```suggestion
    "raoulritter/flux-dev-mlx": {
        "FLUX.1-dev": "flux1-dev.safetensors",
        "vae": "ae.safetensors",
    },
```

2024-09-06 20:54 UTC, ZachNagengast commented on python/src/diffusionkit/mlx/model_io.py
> +        },
```suggestion
    "argmaxinc/mlx-FLUX.1-dev": {
            "vae_encoder": "encoder.",
            "vae_decoder": "decoder.",
        },
```

2024-09-06 21:07 UTC, ZachNagengast commented
Also updated the merge conflicts 👍 Looks like just a linter issue now

2024-09-06 22:10 UTC, ZachNagengast commented
Added a couple changes and got it working locally, just need to fix/remove the tests 👍 
![image](https://github.com/user-attachments/assets/0cee6e05-f48e-46a9-9fc1-caab70b48452)
```bash
diffusionkit-cli --prompt "detailed cinematic dof render of a \
detailed MacBook Pro on a wooden desk in a dim room with items \
around, messy dirty room. On the screen are the letters 'FLUX on \
DiffusionKit' glowing softly. High detail hard surface render" \
--height 768 \
--width 1360 \
--seed 1001 \
--step 50 \
--output ~/Desktop/flux_on_mac.png \
--model-version argmaxinc/mlx-FLUX.1-dev
```

2024-09-06 22:35 UTC, arda-argmax approved these changes
Everything seems to be working 👍 LGTM!
@raoulritter Thank you for your contribution and @ZachNagengast thank you for the pipeline fixes 🙏

2024-09-09 20:24 UTC, mgierschdev commented
Trying to run from this branch and I am getting:
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-66df5923-68833e15000b3b0d21d61def;e6a2d04b-f799-46e3-ab18-23cf484b0657)

Repository Not Found for url: https://huggingface.co/argmaxinc/mlx-FLUX.1-dev/resolve/main/flux1-dev.safetensors.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

2024-09-09 22:05 UTC, ZachNagengast commented
@mgierschdev Thanks for the report, there were some restrictions on the model repo that I've removed now, could you try it again and lmk how it goes?

2024-09-09 23:50 UTC, merged

2024-09-10 01:35 UTC, ZachNagengast commented
@raoulritter This is an awesome contribution, thank you!

2024-09-10 06:50 UTC, raoulritter commented
Hi @ZachNagengast happy to help thanks for fixing the conflicts and nits. I would love to (help) add lora capabilities as well not sure what your team's plan is.